services:
  mongodb:
    image: mongo:7.0
    container_name: project-helper-mongodb
    ports:
      - "27017:27017"
    volumes:
      - project-helper-mongo:/data/db

  redis-stack:
    image: redis/redis-stack-server:7.4.0-v6
    container_name: project-helper-redis
    ports:
      - "6379:6379"
    volumes:
      - project-helper-redis:/data

volumes:
  project-helper-mongo:
  project-helper-redis:
