<script setup lang="ts">
import { nextTick, onMounted, ref } from 'vue'
import { Promotion, RefreshRight } from '@element-plus/icons-vue'
import { api, type ApiResponse } from '../api'

interface Citation { documentId: string; title: string; chunkIndex: number }
interface Action { type: string; entityId: string; summary: string }
interface ChatMessage { role: 'user'|'assistant'; content: string; citations?: Citation[]; actions?: Action[]; error?: boolean }
const conversationId = ref(localStorage.getItem('ph_conversation_id') || crypto.randomUUID())
const input = ref(''), loading = ref(false), messages = ref<ChatMessage[]>([]), stream = ref<HTMLElement | null>(null)
onMounted(() => localStorage.setItem('ph_conversation_id', conversationId.value))
function newConversation() { conversationId.value = crypto.randomUUID(); localStorage.setItem('ph_conversation_id', conversationId.value); messages.value = [] }
async function send() {
  const text = input.value.trim(); if (!text || loading.value) return
  messages.value.push({ role:'user', content:text }); loading.value = true; await nextTick(); stream.value?.scrollTo({ top: stream.value.scrollHeight, behavior:'smooth' })
  try {
    const { data } = await api.post<ApiResponse<{ conversationId:string; answer:string; citations:Citation[]; actions:Action[] }>>('/ai/chat', { message:text, conversationId:conversationId.value })
    conversationId.value = data.data.conversationId; localStorage.setItem('ph_conversation_id', conversationId.value)
    messages.value.push({ role:'assistant', content:data.data.answer, citations:data.data.citations, actions:data.data.actions }); input.value = ''
  } catch { messages.value.push({ role:'assistant', content:'发送失败。请检查 AI 配置或稍后重试；你的输入已保留。', error:true }) }
  finally { loading.value=false; await nextTick(); stream.value?.scrollTo({ top:stream.value.scrollHeight, behavior:'smooth' }) }
}
</script>

<template>
  <div class="chat-page"><header class="page-header"><div><h1>AI assistant</h1><p>Ask about projects, weekly reports, tasks and the public knowledge base</p></div><el-button :icon="RefreshRight" @click="newConversation">New conversation</el-button></header><section class="chat-shell surface"><div ref="stream" class="chat-stream"><div v-if="!messages.length" class="chat-welcome"><span class="ai-mark">AI</span><h2>How can I help?</h2><p>Ask “What are my recent tasks?”, “What is my graduation project?” or search for thesis guidelines.</p><div class="suggestions"><button @click="input='What are my recent tasks?'; send()">What are my recent tasks?</button><button @click="input='What is my graduation project?'; send()">What is my graduation project?</button><button @click="input='Search the thesis formatting requirements'; send()">Search thesis requirements</button></div></div><article v-for="(m,i) in messages" :key="i" :class="['message',m.role,m.error ? 'error':'']"><div class="message-role">{{ m.role === 'user' ? 'You' : 'AI' }}</div><div class="bubble"><p>{{ m.content }}</p><div v-if="m.citations?.length" class="evidence"><strong>Sources</strong><span v-for="c in m.citations" :key="`${c.documentId}-${c.chunkIndex}`">{{ c.title }} · chunk {{ c.chunkIndex + 1 }}</span></div><div v-if="m.actions?.length" class="evidence actions"><strong>Actions</strong><span v-for="a in m.actions" :key="a.entityId">{{ a.type }}: {{ a.summary }}</span></div></div></article><article v-if="loading" class="message assistant"><div class="message-role">AI</div><div class="bubble typing"><i></i><i></i><i></i></div></article></div><div class="composer"><el-input v-model="input" type="textarea" :autosize="{minRows:2,maxRows:6}" resize="none" placeholder="Ask a question..." @keydown.enter.exact.prevent="send" /><el-button type="primary" :icon="Promotion" circle :loading="loading" :disabled="!input.trim()" title="Send" @click="send" /></div><small class="conversation-label">Conversation ID: {{ conversationId }}</small></section></div>
</template>

<style scoped>
.chat-shell { display:flex; flex-direction:column; height:calc(100vh - 138px); min-height:530px; padding:0; overflow:hidden; }.chat-stream { flex:1; overflow:auto; padding:28px clamp(18px,5vw,70px); }.chat-welcome { max-width:620px; margin:60px auto; text-align:center; }.ai-mark { display:grid; place-items:center; width:48px; height:48px; margin:0 auto; color:white; background:var(--green); border-radius:7px; font-weight:800; }.chat-welcome h2 { margin:20px 0 8px; }.chat-welcome p { color:var(--muted); line-height:1.7; }.suggestions { display:flex; flex-wrap:wrap; justify-content:center; gap:8px; margin-top:24px; }.suggestions button { padding:9px 13px; border:1px solid var(--line); border-radius:6px; color:#33453f; background:white; cursor:pointer; }.suggestions button:hover { border-color:var(--green); color:var(--green); }.message { display:grid; grid-template-columns:34px minmax(0,1fr); gap:11px; max-width:780px; margin:0 auto 22px; }.message.user { direction:rtl; }.message.user>* { direction:ltr; }.message-role { width:34px; height:34px; display:grid; place-items:center; border-radius:6px; color:white; background:#64736e; font-size:11px; font-weight:700; }.assistant .message-role { background:var(--green); }.bubble { width:fit-content; max-width:90%; padding:12px 15px; border:1px solid var(--line); border-radius:7px; background:white; }.user .bubble { margin-left:auto; color:white; background:#23493d; border-color:#23493d; }.bubble p { margin:0; line-height:1.7; white-space:pre-wrap; }.message.error .bubble { color:#8f241d; background:#fff3f2; border-color:#f3cbc7; }.evidence { display:grid; gap:5px; margin-top:12px; padding-top:10px; border-top:1px solid #dce4e0; font-size:12px; color:var(--muted); }.actions { color:#176b4d; }.typing i { display:inline-block; width:6px; height:6px; margin:0 2px; border-radius:50%; background:#8a9994; animation:pulse 1s infinite alternate; }.typing i:nth-child(2){animation-delay:.2s}.typing i:nth-child(3){animation-delay:.4s}@keyframes pulse{to{opacity:.25;transform:translateY(-2px)}}.composer { display:flex; align-items:flex-end; gap:10px; padding:15px 18px 8px; border-top:1px solid var(--line); background:#fafcfb; }.composer .el-button { flex:0 0 auto; width:42px; height:42px; }.conversation-label { display:block; padding:0 20px 11px; color:#9aa6a2; background:#fafcfb; overflow:hidden; text-overflow:ellipsis; white-space:nowrap; }.chat-page .page-header { margin-bottom:16px; }
@media(max-width:800px){.chat-shell{height:calc(100vh - 150px)}.chat-stream{padding:20px 12px}.chat-welcome{margin:30px auto}.bubble{max-width:96%}}
</style>
